### ISSUE TITLE
Disable or change the shared description

### ISSUE THREAD

**Issue by davidmadon** [superwebshare/super-web-share#26]
Hi,
Thanks for an awesome plugin!

I'd like a way to change/disable the text included in the share message. (The meta description)

Use case:
1. I want to share only the page URL with no additional text. (Most apps today will anyways include a link preview with title and favicon)
2. I want to include a specific call to action in the shared content, different from the meta description.

I feel this would be a great setting to have in the metabox on each page. If left empty just fallback to the current behaviour.

Thanks!

**Comment by josevarghese** [comment]
Hi @davidmadon 

Thanks for using Super Web Share and sharing the details to understand the feature request better. I understand that you would like an option to disable the output for the description, as some social media show the description within the preview. Frankly, this is something within our roadmap, but before that, we need to work on some more features on my mind. So I am not able to share any ETA at this moment.

Could you [please add this feature request over here](https://github.com/superwebshare/super-web-share/discussions/2), so we can track the feature requests better based on the interests of other users and can prioritize them better? 

Looking forward.
